### PR TITLE
Build on all fsproject branches

### PR DESCRIPTION
**Pull request by wallymathieu**
This means that for for some pull requests we get double builds

### CODE REVIEW

**Comment by adz** [comment]
Btw still doesn't build docs for me on Linux with dotnetcore only due to net47 ref... Will try on Windows later today

**Comment by adz** [comment]
On windows I installed dotnetcore 3.1 and framework 4.8.
When i run "dotnet fsi buildDocs.fsx" it fails in similar way:
https://gist.github.com/adz/57ef4311771121c7589c5091eef0b5f0

**Comment by wallymathieu** [comment]
@adz I have a PR where I've started to convert from paket-implicit dependency #275

**Comment by adz** [comment]
Cool! I'll give it a try...

**Pull request merged**
