### PR TITLE
net 7.0.200 for Fable

### PR DESCRIPTION
**Pull request by wallymathieu**
Use fable with .net 7 installed.  
See https://github.com/fsprojects/FSharpPlus/pull/525 for why we did not upgrade to net7 for Fable CI

### CODE REVIEW

**Comment by wallymathieu** [comment]
@anpin no, it would not fix any issue since this is only build related

**Comment by wallymathieu** [comment]
The build problem you mention looks odd since there should be ifdefs in order to avoid using list collector for Fable.

**Comment by reinux** [comment]
I'm getting a bunch of "not defined" errors using this with the just-released Fable 4. Is this related?

```
.\src\Main.fs(4,17): (4,21) error FSHARP: The namespace 'Lens' is not defined. (code 39)
.\src\Main.fs(19,9): (19,13) error FSHARP: The value or constructor 'view' is not defined. (code 39)
.\src\Main.fs(60,21): (60,26) error FSHARP: The value or constructor '_Some' is not defined. Maybe you want one of the following:
   Some (code 39)
.\src\Main.fs(70,19): (70,24) error FSHARP: The value or constructor '_Some' is not defined. Maybe you want one of the following:
   Some (code 39)
.\src\Main.fs(72,38): (72,43) error FSHARP: The value or constructor '_Some' is not defined. Maybe you want one of the following:
   Some (code 39)
.\src\Main.fs(136,7): (136,11) error FSHARP: The value or constructor 'setl' is not defined. Maybe you want one of the following:
   Set
   set
   Set
   seq
   Seq (code 39)
.\src\Main.fs(222,26): (222,32) error FSHARP: The value or constructor 'filter' is not defined. Maybe you want one of the following:   Feliz (code 39)
.\src\Main.fs(223,26): (223,30) error FSHARP: The value or constructor 'bind' is not defined. Maybe you want one of the following:
   Binary
   int (code 39)
.\src\fable_modules\FSharpPlus.1.4.0\Extensions\List.fs(90,20): (90,41) error FABLE: Microsoft.FSharp.Core.CompilerServices.ListCollector`1.Add is not supported by Fable
.\src\fable_modules\FSharpPlus.1.4.0\Extensions\List.fs(91,8): (91,21) error FABLE: Microsoft.FSharp.Core.CompilerServices.ListCollector`1.Close is not supported by Fable
.\src\fable_modules\FSharpPlus.1.4.0\Control\Comonad.fs(18,8): (18,44) error FABLE: System.Threading.Tasks.Task`1.get_Result is not supported by Fable
```

**Comment by wallymathieu** [comment]
@reinux @anpin see #539

**Pull request merged**
