### PR TITLE
Bifoldable abstraction

### PR DESCRIPTION
**Pull request by smoothdeveloper**
This is going to be a long and non-optimal journey towards #213.

Opening here to leverage the CI and getting input from people aware of idioms of implementation in this library.

### CODE REVIEW

**Comment by gusty** [comment]
Looks like there is a Monoid constraint in all Bifoldable functions.

Now, for Result / Choice that constraint is not really an issue, since there's always a single value, so you don't need to fold them into one.

The question is, should we remove that restriction? Or should we keep it?

If we keep it, we'll end up with `bifoldMap` which would be like a generic `either` but with the Monoid restriction.

The monoid restriction is not that bad in F#+ since many types are monoids, including numeric types which in other languages like Haskell are not.

Thoughts ?

**Comment by smoothdeveloper** [comment]
@gusty, to add to your comment, this is what I get in ghci:

> :k Bifoldable
```haskell
Bifoldable :: (* -> * -> *) -> Constraint
```

> :t bifoldMap
```haskell
bifoldMap :: (Bifoldable p, Monoid m) => (a -> m) -> (b -> m) -> p a b -> m
```

> :t bifoldr
```haskell
bifoldr :: Bifoldable p => (a -> c -> c) -> (b -> c -> c) -> c -> p a b -> c
```
> :t bifold
```haskell
bifold :: (Bifoldable p, Monoid m) => p m m -> m
```

The type class itself doesn't have constraint for `Monoid`, but it appears on `bifoldMap` and `bifold`, while `bifoldr` is unrestricted.

**Comment by gusty** [comment]
Regarding the names.
Normally

In Haskell `fold` is called `foldr`
.. `foldback` is `foldl`
.. `sum` is `fold`

So I think we rename `bifold` to `bisum`.

Then `bifold` becames available again. Should we add the Haskell's `foldl` implementation?

**Comment by wallymathieu** [comment]
Perhaps something to add to https://github.com/fsprojects/FSharp.Compatibility once this is merged?

**Comment by gusty** [comment]
I think we can update the reference, specially once we're in v1.1 (very soon I hope)

**Comment by wallymathieu** [comment]
The above looks amenable for ploeh [recent example of [impure/pure/impure](https://blog.ploeh.dk/2019/12/02/refactoring-registration-flow-to-functional-architecture/) since he uses a map that goes over both cases.

**Comment by gusty** [comment]
@wallymathieu I think he speaks there more about Bitraversable, which should be the next think to add ;)

**Comment by smoothdeveloper** [comment]
@gusty just standing on the shoulders of the SRTP giants! 🙂

**Comment by wallymathieu** [comment]
Thanks @gusty ! 😄

**Pull request merged**
