### PR TITLE
Rename IReadOnlyList.add to trySetItem

### PR DESCRIPTION
**Pull request by wallymathieu**
Also added some documentation while at it

### CODE REVIEW

**Comment by gusty** [comment]
I'm still not sure which one aligns better: `trySetItem` or `trySetValue`.

I'm gathering evidence of actual naming to see which one is the de-facto standard.

**Comment by wallymathieu** [comment]
Good question, there are some merits to both. Though tryItem is already declared on the module, why perhaps we should rename both in that case

**Comment by cannorin** [comment]
The intuition behind the naming of `tryItem` would be  `get_Item` and `set_Item`, so I think `try{Get,Set}Item` is the best option. But since there are so many `item/tryItem` already in the library, it might not worth renaming all of them to `getItem/tryGetItem`.

**Comment by wallymathieu** [comment]
Yes, tryGetItem would be neat to have.

**Pull request merged**
