### PR TITLE
Rename string trim functions

### PR DESCRIPTION
**Pull request by cmeeren**
As requested in https://github.com/fsprojects/FSharpPlus/issues/288#issuecomment-619355229

### CODE REVIEW

**Comment by wallymathieu** [comment]
Looks good. Looks like `trimboth` is used in python. Another alternative is to use the word `strip`.

**Comment by wallymathieu** [comment]
It would be good to hear some people chime in here 😃

**Comment by cmeeren** [comment]
I think we should stick to some version of `trim` because it's what .NET users expect.

Alternatives to `trimBoth` are `trimStartEnd`, or `trimChars` (though then it's not consistent with `trimStart` and `trimEnd`).

**Comment by wallymathieu** [comment]
That's true. Let's see what people says 😃

**Comment by gusty** [comment]
I think I would be in favor of this change, but of course in case we approve it, it will have to be for v2.0

In the meantime it would be interesting to hear other voices. Maybe @cannorin can comment as he added many string functions to the lib.

**Pull request merged**
