### PR TITLE
Bugfix: NonEmptyList.map2Shortest, Fix FsCheck tests

### PR DESCRIPTION
**Pull request by 3Rafal**
Change FsCheck usage to a version that throws exceptions when properties are not fulfilled.

### CODE REVIEW

**Comment by wallymathieu** [comment]
I've added some code to make the tests green. So it looks like you have found a bug 😃 !

**Comment by 3Rafal** [comment]
> I've added some code to make the tests green @3Rafal. So it looks like you have found a bug 😃 !

Thanks @wallymathieu ! I think we're fine now 🙂
What do you think @gusty ?

**Comment by 3Rafal** [comment]
This resolves #411

**Comment by wallymathieu** [comment]
I've renamed the PR to match what it does. I'm thinking of merging it and putting it on the v1.1 track for release later on today.

**Review by gusty — APPROVED** [review]

**Comment by wallymathieu** [comment]
Turns out we have not yet released the map2shortest on the v1.1 track, so it goes into the v1.2 track 😄

**Pull request merged**
